//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CardsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaveTable
    {
        public long saveId { get; set; }
        public byte[] savedData { get; set; }
        public string userId { get; set; }
        public int gameId { get; set; }
        public string saveName { get; set; }
    
        public virtual GameTable GameTable { get; set; }
    }
}
